<?php


namespace App\Controller;


use App\Model\ShowEventsModel;

class Events extends Table
{
    protected string $tableName = "events";

    public function __construct()
    {
        parent::__construct();
        $config = include __DIR__ . "/../../config.php";
        $config["table"] = $this->tableName;
        $this->model = new ShowEventsModel($config);
    }

    public function actionShowAdd(): void
    {
        parent::actionShowAdd(); // TODO: Change the autogenerated stub
        $this->view->setTemplate("Events/add_edit");
    }

    public function actionShowEdit(): void
    {
        parent::actionShowEdit(); // TODO: Change the autogenerated stub
        $this->view->setTemplate("Events/add_edit");
    }

    public function actionShow(): void
    {
        parent::actionShow(); // TODO: Change the autogenerated stub
        $this->view->setTemplate("Events/show");
    }

    public function actionShowNews(): void
    {
        $this
            ->view
            ->addData([
                "new" => $this->model->getRow($_GET['id']),
                "comments" => $this->model->getEventsComments($_GET['id']),
                "countLike" => $this->model->countLike($_GET['id'])
            ])
            ->setTemplate("Showevents/new");
    }

    public function actionAdd(): void
    {
//        print_r($_FILES);
//        unset($_POST['picture']);
        $_POST['picture'] = $_FILES['picture']['name'];
        $id = $this->model->ins($_POST);
        move_uploaded_file(
            $_FILES['picture']['tmp_name'],
            __DIR__ . "/../../public/images/event/{$id}_" . $_FILES['picture']['name']
        );
        $this->redirect("?type={$this->getCurrentClass()}&action=show");

    }
}