<?php


namespace App\Controller;


use App\Model\ShowEventsModel;


class Showevents extends Events
{
    public function __construct()
    {
        parent::__construct();
        $config = include __DIR__ . "/../../config.php";
        $config["table"] = $this->tableName;
        $this->model = new ShowEventsModel($config);
    }

    public function actionShowEdit(): void
    {
        $this->redirect("/");
    }

    public function actionShowAdd(): void
    {
        $this->redirect("/");
    }

    public function actionDel(): void
    {
        $this->redirect("/");
    }

    public function actionAdd(): void
    {
        $this->redirect("/");
    }

    public function actionEdit(): void
    {
        $this->redirect("/");
    }

    public function actionShow(): void
    {
        parent::actionShow(); // TODO: Change the autogenerated stub
        $this->view->setTemplate("Showevents/show");
    }

    public function actionShowNews(): void
    {
        $this
            ->view
            ->addData([
                "new" => $this->model->getRow($_GET['id']),
                "comments" => $this->model->getEventsComments($_GET['id']),
                "countLike" => $this->model->countLike($_GET['id'])
            ])
            ->setTemplate("Showevents/new");
    }

    public function actionAddComment(): void
    {
        if (isset($_SESSION["user"]["id"])) {
            $this->model->addComment($_POST["text"], $_POST["events_id"], $_SESSION["user"]["id"]);
            $this->redirect("?type=showevents&action=showNews&id=" . $_POST["events_id"]);
        } else {
            $this->redirect("/");
        }
    }

    public function actionAddLike()
    {
        if (isset($_SESSION["user"]["id"]) && !empty($_SESSION["user"]["id"])) {
            if (!$this->model->chekLike($_GET["event_id"], $_SESSION["user"]["id"])) {
                $this->model->setTableName("Likes")->ins([
                    "events_id" => $_GET["event_id"],
                    "users_id" => $_SESSION["user"]["id"]]);
            }
        }
        $this->redirect("?type=showevents&action=showNews&id=" . $_GET["event_id"]);
    }

}